"""init_tables

Revision ID: 600987b7f446
Revises: 
Create Date: 2026-08-13 15:19:07.212645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600987b7f446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限 ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='角色-权限关联表'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户-角色关联表'
    )
    op.create_index('ix_depts_status_deleted', 'depts', ['status', 'is_deleted'], unique=False)
    op.create_index('ix_op_logs_created_status', 'operation_logs', ['created_at', 'status'], unique=False)
    op.create_index('ix_op_logs_module_created', 'operation_logs', ['module', 'created_at'], unique=False)
    op.create_index('ix_permissions_parent_type', 'permissions', ['parent_id', 'type'], unique=False)
    op.create_index('ix_permissions_status_deleted', 'permissions', ['status', 'is_deleted'], unique=False)
    op.create_index('ix_roles_status_deleted', 'roles', ['status', 'is_deleted'], unique=False)
    op.alter_column('users', 'status',
               existing_type=mysql.INTEGER(),
               comment='状态:1-启用 0-禁用',
               existing_comment='状态：1-启用 0-禁用',
               existing_nullable=False)
    op.create_index('ix_users_status_deleted', 'users', ['status', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_status_deleted', table_name='users')
    op.alter_column('users', 'status',
               existing_type=mysql.INTEGER(),
               comment='状态：1-启用 0-禁用',
               existing_comment='状态:1-启用 0-禁用',
               existing_nullable=False)
    op.drop_index('ix_roles_status_deleted', table_name='roles')
    op.drop_index('ix_permissions_status_deleted', table_name='permissions')
    op.drop_index('ix_permissions_parent_type', table_name='permissions')
    op.drop_index('ix_op_logs_module_created', table_name='operation_logs')
    op.drop_index('ix_op_logs_created_status', table_name='operation_logs')
    op.drop_index('ix_depts_status_deleted', table_name='depts')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
